/**
 * Store screenshot headlines and order. `ios` / `android` name the finished job used for each
 * platform (Map and Profile have real Android captures because they show the platform's map).
 * Line breaks are set by hand (\n) so no headline ends on a single orphaned word.
 * The first three are the ones people see in search results. Mirrored in FINALIZE.md (A3).
 * The wording follows STORE_LISTING.md for each language, and the app's own terms
 * (e.g. IT "post", DE "Reisepass", KO "컬렉션").
 */
module.exports = [
    {
        name: 'feed',
        ios: 'feed-dark-en',
        android: 'feed-dark-en',
        en: "See the world through\ntravelers' eyes",
        tr: 'Dünyayı gezginlerin\ngözünden gör',
        es: 'Mira el mundo con\nojos de viajero',
        fr: 'Le monde vu par\nles voyageurs',
        de: 'Die Welt mit den Augen\nvon Reisenden sehen',
        pt: 'Veja o mundo pelos\nolhos de viajantes',
        it: 'Il mondo visto con gli\nocchi dei viaggiatori',
        ru: 'Мир глазами\nпутешественников',
        ja: '旅人の目で\n世界を見よう',
        ko: '여행자의 눈으로\n세상을 보세요',
        zh: '用旅行者的眼睛\n看世界',
        ar: 'شاهد العالم\nبعيون المسافرين',
    },
    {
        name: 'profile',
        ios: 'profile-dark-en',
        android: 'profile-light-android-en',
        en: 'Your passport,\nstamped with memories',
        tr: 'Anılarla damgalanmış\npasaportun',
        es: 'Tu pasaporte,\nsellado de recuerdos',
        fr: 'Votre passeport,\ntamponné de souvenirs',
        de: 'Dein Reisepass,\nvoller Erinnerungen',
        pt: 'Seu passaporte,\ncarimbado de memórias',
        it: 'Il tuo passaporto,\ntimbrato di ricordi',
        ru: 'Ваш паспорт,\nполный воспоминаний',
        ja: '思い出のスタンプで\nいっぱいのパスポート',
        ko: '추억의 도장이\n가득한 여권',
        zh: '盖满回忆印章的\n护照',
        ar: 'جواز سفرك،\nمختوم بالذكريات',
    },
    {
        name: 'map',
        ios: 'map-dark-en',
        android: 'map-light-android-en',
        en: "Pin every place\nyou've been",
        tr: 'Gittiğin her yeri\nharitana işle',
        es: 'Marca cada lugar\nque has visitado',
        fr: 'Épinglez chaque lieu\nque vous avez visité',
        de: 'Markiere jeden Ort,\nan dem du warst',
        pt: 'Marque cada lugar\nonde você esteve',
        it: 'Segna ogni luogo\nin cui sei stato',
        ru: 'Все места,\nгде вы побывали',
        ja: '訪れた場所を\nすべてマップに',
        ko: '다녀온 모든 곳을\n지도에 표시하세요',
        zh: '在地图上标记\n你去过的每个地方',
        ar: 'ثبّت كل مكان\nزرته على الخريطة',
    },
    {
        name: 'explore',
        ios: 'explore-dark-en-fix',
        android: 'explore-dark-en-fix',
        en: 'Find your next\ndestination',
        tr: 'Sıradaki rotanı\nkeşfet',
        es: 'Encuentra tu\npróximo destino',
        fr: 'Trouvez votre\nprochaine destination',
        de: 'Finde dein\nnächstes Reiseziel',
        pt: 'Encontre seu\npróximo destino',
        it: 'Trova la tua\nprossima meta',
        ru: 'Найдите следующее\nнаправление',
        ja: '次の旅先を\n見つけよう',
        ko: '다음 여행지를\n찾아보세요',
        zh: '发现你的\n下一个目的地',
        ar: 'اعثر على\nوجهتك القادمة',
    },
    {
        name: 'city',
        ios: 'city-dark-en',
        android: 'city-dark-en',
        en: 'Every city,\ntold by travelers',
        tr: 'Her şehir,\ngezginlerin kaleminden',
        es: 'Cada ciudad,\ncontada por viajeros',
        fr: 'Chaque ville,\nvue par ses voyageurs',
        de: 'Jede Stadt,\nerzählt von Reisenden',
        pt: 'Cada cidade,\ncontada por viajantes',
        it: 'Ogni città,\nraccontata dai viaggiatori',
        ru: 'Города глазами\nпутешественников',
        ja: 'どの街も、\n旅人が語る',
        ko: '모든 도시,\n여행자가 들려주는 이야기',
        zh: '每座城市，\n由旅行者讲述',
        ar: 'كل مدينة،\nبرواية المسافرين',
    },
    {
        name: 'new-post',
        ios: 'newpost-dark-en',
        android: 'newpost-dark-en',
        en: 'Turn photos into\ntravel stories',
        tr: 'Fotoğraflarını seyahat\nhikâyesine dönüştür',
        es: 'Convierte tus fotos\nen historias de viaje',
        fr: 'Vos photos deviennent\ndes récits de voyage',
        de: 'Aus Fotos werden\nReisegeschichten',
        pt: 'Transforme fotos em\nhistórias de viagem',
        it: 'Trasforma le foto in\nstorie di viaggio',
        ru: 'Превращайте фото\nв истории о поездках',
        ja: '写真を\n旅のストーリーに',
        ko: '사진을\n여행 이야기로',
        zh: '把照片\n变成旅行故事',
        ar: 'حوّل صورك\nإلى قصص سفر',
    },
    {
        name: 'messages',
        ios: 'letters-dark-en',
        android: 'letters-dark-en',
        en: 'Plan the next trip\ntogether',
        tr: 'Sonraki yolculuğu\nbirlikte planla',
        es: 'Planea el próximo\nviaje en compañía',
        fr: 'Préparez ensemble\nle prochain voyage',
        de: 'Plant die nächste\nReise gemeinsam',
        pt: 'Planejem juntos\na próxima viagem',
        it: 'Organizzate insieme\nil prossimo viaggio',
        ru: 'Планируйте\nпоездку вместе',
        ja: '次の旅を\n一緒に計画',
        ko: '다음 여행을\n함께 계획하세요',
        zh: '一起规划\n下一次旅行',
        ar: 'خطّطوا للرحلة\nالقادمة معًا',
    },
    {
        name: 'settings',
        ios: 'settings-dark-en',
        android: 'settings-dark-en',
        en: 'Your journal,\nin 12 languages',
        tr: 'Günlüğün,\n12 dilde',
        es: 'Tu diario,\nen 12 idiomas',
        fr: 'Votre carnet,\nen 12 langues',
        de: 'Dein Tagebuch,\nin 12 Sprachen',
        pt: 'Seu diário,\nem 12 idiomas',
        it: 'Il tuo diario,\nin 12 lingue',
        ru: 'Ваш дневник\nна 12 языках',
        ja: 'あなたの日記を、\n12言語で',
        ko: '나의 일기,\n12개 언어로',
        zh: '你的日记，\n支持 12 种语言',
        ar: 'مذكراتك،\nبـ 12 لغة',
    },
];
